[env]
TERM = "xterm-256color"
SHELL = "/opt/homebrew/bin/fish"
LANG = "ja_JP.UTF-8"

[font]
size = 13.5

[terminal]
shell = { program = "/opt/homebrew/bin/fish" }

[font.normal]
family = "Hack Nerd Font Mono"
