[[plugins]]
repo = 'Shougo/dein.vim'

#[[plugins]]
#repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
	runtime! plugins/defx.vim
'''

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {'colorscheme': 'solarized dark'}
	runtime! ./plugins/lightline.vim
'''

# vcs
[[plugins]]
repo = 'tpope/vim-fugitive'

# development

[[plugins]]
repo = 'mileszs/ack.vim'
hook_add = '''
	runtime! plugins/ack.vim
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
	runtime! ./plugins/fzf.vim
'''

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'

[[plugins]]
repo = "neoclide/coc.nvim"
merge = 0
rev = "release"
hook_add = '''
	runtime! plugins/coc.vim
'''

[plugins.ftplugin]
defx = '''
call defx#custom#option('_', {
    \ 'columns': 'indent:git:icons:filename',
    \ 'show_ignored_files': 1,
    \ })
	runtime! plugins/defx.vim
'''
