[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {'colorscheme': 'solarized dark'}
'''

# vcs
[[plugins]]
repo = 'tpope/vim-fugitive'

# development
[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'mileszs/ack.vim'

