add_newline = true

format = '''
[|───────────────────>](bold green) $all'''

[directory]
truncation_length = 100
truncate_to_repo = false

[git_status]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[time]
disabled = false
